FROM python:3.6.5-jessie

ARG PROJECT_ROOT=/workdir/src/
RUN mkdir -p ${PROJECT_ROOT}

WORKDIR ${PROJECT_ROOT}

RUN pip install pipenv
COPY ./Dockerrun.dev.sh ./

CMD ["sh", "Dockerrun.dev.sh", "pipenv", "run", "python", "app.py"]
