FROM golang

WORKDIR /go/src/residential_map_api
RUN go get github.com/codegangsta/gin
RUN go get github.com/golang/dep/cmd/dep
RUN git clone https://ff9c83fe555ed8838527699688e388dec6031bad:x-oauth-basic@github.com/katakatataan/residential_map_api.git

CMD ["sh", "Dockerrun.dev.sh", "gin", "-p","2000","-a","1323","run","main.go"]
